version: v0

runs:
  - name: Application Checks
    tasks:
      - name: checkout code
        runtime:
          containers:
            - image: harryadel/unchained-commerce-main:1.0      
        steps:
          - clone:
          - save_to_workspace:
              contents:
                - source_dir: .
                  dest_dir: .
                  paths:
                    - '**'
      - name: build docker image
        runtime:
          containers:
            - image: gcr.io/kaniko-project/executor:debug
        shell: /busybox/sh
        steps:
          - restore_workspace:
              dest_dir: .
          #- run: /kaniko/executor --no-push
          - run: /kaniko/executor --destination registry/image
        depends:
          - checkout code
      - name: test stuff 
        run:
            name: lint
          - command: meteor npm run lint:ci      
       steps:
         - clone:
         - run:
             name: test
             command: meteor npm run test:ci