version: v0

runs:
  - name: Application Checks
    tasks:
      - name: checkout code
        runtime:
          containers:
            - image: geoffreybooth/meteor-base:1.11.1
        steps:
          - clone:
          - run:
              name: install
              command: meteor npm install
          - run:
              name: lint
              command: meteor npm run lint:ci
          - run:
              name: test
              command: meteor npm run test:ci
