version: v0

runs:
  - name: Checks
    tasks:
      - name: run checks
        runtime:
          containers:
            - image: geoffreybooth/meteor-base:1.11.1
        steps:
          - run:
              name: install ssh-client    
              command: apt-get install ssh-client -y
          - clone:
          - run:
              name: install
              command: meteor npm install
          - run:
              name: lint
              command: meteor npm run lint:ci
          - run:
              name: test
              command: meteor npm run test:ci
