version: v0

runs:
  - name: Application Checks
    tasks:
      - name: checkout code
        runtime:
          containers:
            - image: harryadel/unchained-commerce-main:1.0
        steps:
          - clone:
          - run: meteor npm run lint:ci
          - run: meteor npm run test:ci
        # depends:
        #   - checkout code
      # - name: run checks
      #   steps:
      #     - run:
      #         name: lint
      #         command: meteor npm run lint:ci
      #     - run:
      #         name: test
      #         command: meteor npm run test:ci
