introspection: http://localhost:4010/graphql
servers:
  - url: https://engine.unchained.shop/graphql
    description: Development Server
info:
  description: |
    Welcome to unchained API documentation
  version: 1.0.0
  title: UnchainedShop API
  termsOfService: "https://github.com/unchainedshop/unchained/blob/master/docs/contributing.md"
  contact:
    email: hello@unchained.shop
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
